<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */

namespace MSBios\CPanel;

$this->headScript()
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/switch.min.js'))
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/switchery.min.js'))
    ->appendFile($this->basePath('limitless/assets/js/plugins/forms/styling/uniform.min.js'));
?>

    <div class="row">
        <div class="col-md-12">

            <?php if (!$this->paginator->count()) : ?>

                <div class="alert alert-info no-border" role="alert">
                    <h4><?= $this->translate('Information message'); ?></h4>
                    <p><?= $this->translate('The database is not created at the moment no layout, click "Add new entity" to start working with the layout.'); ?></p>
                    <p>
                        <a href="<?= $this->url($this->config->getRouteName(), ['action' => 'add']); ?>"
                           class="btn btn-info"><?= $this->translate('Create new layout'); ?></a>
                    </p>
                </div>

            <?php else: ?>

                <div class="panel panel-flat">

                    <div class="panel-heading">
                        <h6 class="panel-title">&nbsp;<a class="heading-elements-toggle"><i class="icon-more"></i></a>
                        </h6>
                        <div class="heading-elements">

                            <div class="heading-btn">
                                <form class="heading-form" action="#">
                                    <div class="form-group has-feedback">
                                        <input type="search" class="form-control" placeholder="Search...">
                                        <div class="form-control-feedback">
                                            <i class="icon-search4 text-size-base text-muted"></i>
                                        </div>
                                    </div>
                                </form>

                                <a href="<?= $this->url($this->config->get('route_name'), [
                                    'action' => 'add'
                                ]); ?>" class="btn btn-success"><?= $this->translate('Create new layout'); ?></a>
                            </div>


                            <form class="heading-form hide" action="#">
                                <div class="form-group">
                                    <div class="input-group">
                                        <input type="text" class="form-control" placeholder="Search..." width="200px">
                                        <div class="input-group-btn">
                                            <a href="<?= $this->url($this->config->get('route_name'), ['action' => 'add']); ?>"
                                               class="btn btn-success"><?= $this->translate('Create new layout'); ?></a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                    <div class="panel-body">

                        <table class="table table-striped table-hover mails m-0 table table-actions-bar">
                            <thead>
                            <tr>
                                <th><?= $this->translate('Title'); ?></th>
                                <th><?= $this->translate('Template'); ?></th>
                                <th width="1px" class="text-center">
                                    <?= $this->translate('Actions'); ?>
                                </th>
                            </tr>
                            </thead>

                            <tbody>
                            <?php /** @var \MSBios\Resource\Entity\Layout $item */ ?>
                            <?php foreach ($this->paginator as $item): ?>
                                <tr>
                                    <td><?= $this->escapeHtml($item->getTitle()); ?></td>
                                    <td><?= $this->escapeHtml($item->getTemplate()); ?></td>
                                    <td class="text-center">

                                        <?php /** @var string $identifierTrashModal */ ?>
                                        <?php $identifierTrashModal = "modal-confirm-{$item->getId()}"; ?>

                                        <ul class="icons-list">
                                            <li>
                                                <a href="<?= $this->url($this->config->get('route_name'), [
                                                    'action' => 'edit', 'id' => $item->getId()
                                                ]); ?>">
                                                    <i class="icon-pencil"></i>
                                                </a>
                                            </li>

                                            <li class="text-danger-600">
                                                <a href="#"
                                                   data-toggle="modal"
                                                   data-target="#<?= $identifierTrashModal; ?>">
                                                    <i class="icon-trash"></i>
                                                </a>
                                            </li>

                                        </ul>

                                        <!-- Modal -->
                                        <div class="modal fade" id="<?= $identifierTrashModal; ?>" tabindex="-1"
                                             role="dialog">
                                            <div class="modal-dialog modal-sm" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h4 class="modal-title">Are you sure?</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p>Do you want to delete the entry?</p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button"
                                                                class="btn btn-default"
                                                                data-dismiss="modal">
                                                            Cancel
                                                        </button>
                                                        <a href="<?= $this->url($this->config->get('route_name'), [
                                                            'action' => 'drop',
                                                            'id' => $item->getId()
                                                        ]); ?>" class="btn btn-primary">
                                                            Yes, delete it!
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            </tbody>
                        </table>

                        <?= $this->paginationControl($this->paginator, 'sliding', 'partial/pagination.phtml', [
                            'route' => $this->config->get('route_name')
                        ]); ?>

                    </div>

                </div>

            <?php endif; ?>

        </div> <!-- end col -->
    </div>

    <?php
// $this->headScript()
//     ->prependFile($this->basePath('limitless/assets/js/pages/form_checkboxes_radios.js'));
?>