<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\CPanel;

/** @var string $target */
$target = md5(md5(time()) . $this->identifier);
?>

<ul class="icons-list">
    <li>
        <a href="<?= $this->url($this->matchedRouteName, [
            'action' => 'edit', 'id' => $this->identifier
        ]); ?>">
            <i class="icon-pencil"></i>
        </a>
    </li>
    <li class="text-danger-600">
        <a href="#" data-toggle="modal" data-target="#<?= $target; ?>">
            <i class="icon-trash"></i>
        </a>
    </li>
</ul>

<!-- Modal -->
<div class="modal fade" id="<?= $target; ?>" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">
                    <?= $this->translate('Are you sure?'); ?>
                </h4>
            </div>
            <div class="modal-body">
                <p><?= $this->translate('Do you want to delete the entry?'); ?></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default">
                    <?= $this->translate('Cancel'); ?>
                </button>
                <a href="<?= $this->url($this->matchedRouteName, [
                    'action' => 'drop', 'id' => $this->identifier
                ]); ?>" class="btn btn-primary">
                    <?= $this->translate('Yes, delete it!'); ?>
                </a>
            </div>
        </div>
    </div>
</div>