<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\CPanel;

/** @var array $page */
$page = $this->navigation()->findActive(Navigation\Sidebar::class);
if (!$page['depth']) return;

/** @var \Zend\Navigation\Page\Mvc $current */
$current = $page['page'];
?>

<!-- Page header -->
<div class="page-header">
    <div class="page-header-content">
        <div class="page-title">
            <h4>
                <i class="icon-arrow-left52 position-left"></i>
                <span class="text-semibold"><?= $current->getLabel(); ?></span>
            </h4>
        </div>

        <div class="heading-elements">
            <div class="heading-btn-group">
                <a href="#" class="btn btn-link btn-float has-text"><i class="icon-bars-alt text-primary"></i><span>Statistics</span></a>
                <a href="#" class="btn btn-link btn-float has-text"><i class="icon-calculator text-primary"></i> <span>Invoices</span></a>
                <a href="#" class="btn btn-link btn-float has-text"><i class="icon-calendar5 text-primary"></i> <span>Schedule</span></a>
            </div>
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-component">
        <ul class="breadcrumb">

            <li>
                <a href="/">
                    <i class="icon-earth position-left"></i> Suite
                </a>
            </li>

            <li>
                <a href="index.html">
                    Dashboard
                </a>
            </li>

            <?php foreach ($this->pages as $key => $page): ?>
                <?php if ($key < count($this->pages) - 1): ?>
                    <li>
                        <a href="<?= $page->getHref(); ?>">
                            <?= $page->getLabel(); ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <?= $page->getLabel(); ?>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>

        <ul class="breadcrumb-elements">
            <li><a href="#"><i class="icon-comment-discussion position-left"></i> Support</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="icon-gear position-left"></i>
                    Settings
                    <span class="caret"></span>
                </a>

                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="#"><i class="icon-user-lock"></i> Account security</a></li>
                    <li><a href="#"><i class="icon-statistics"></i> Analytics</a></li>
                    <li><a href="#"><i class="icon-accessibility"></i> Accessibility</a></li>
                    <li class="divider"></li>
                    <li><a href="#"><i class="icon-gear"></i> All settings</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>
<!-- /page header -->