<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\Portal\CPanel;

use Zend\Stdlib\ArrayUtils;

/** @var \Zend\Form\ElementInterface $element */
$element = $this->element;

/** @var array $messages */
$messages = $element->getMessages();

/** @var boolean $hasError */
$hasError = count($messages);

/** @var array $attributes */
$element->setAttributes(ArrayUtils::merge($this->attributes ?: [], [
    'id' => $element->getName(),
    'class' => 'form-control'
]));

/** @var array $options */
$options = ArrayUtils::merge([
    'label_class' => 'col-md-2 control-label',
    'div_class' => 'col-md-10'
], $this->options ?: []);

?>
<div class="form-group <?php if ($hasError): ?>has-error has-feedback<?php endif; ?>">
    <label class="<?= $options['label_class']; ?>" for="<?= $element->getName(); ?>">
        <?= $this->label; ?>:
        <?php if ($element->hasAttribute('required')): ?>
            <span class="text-danger">*</span>
        <?php endif; ?>
    </label>
    <div class="<?= $options['div_class']; ?>">
        <?= $this->formCheckbox($element); ?>
        <?php if (count($messages)): ?>
            <span class="glyphicon glyphicon-remove form-control-feedback"></span>
            <span class="help-block">
                <?php foreach ($messages as $message): ?>
                    <small><?= $message; ?></small>
                <?php endforeach; ?>
            </span>
        <?php endif; ?>

    </div>
</div>