<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
?>
<div class="text-right">
    <?= $this->formRow($this->form->get('id')); ?>
    <a href="<?= $this->url($this->route); ?>" class="btn btn-link">
        <?= $this->translate('Back to the list of entries'); ?>
    </a>
    <button type="reset" class="btn btn-default">
        <?= $this->translate('Reset'); ?>
    </button>
    <?= $this->partial('partial/submit-button.phtml'); ?>
</div>