<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\CPanel;

/** @var string $url */
use Zend\Stdlib\ArrayUtils;

$url = function ($view, $params = [], $options = []) {
    /** @var array $params */
    $params = ArrayUtils::merge($view->params ?: [], $params) ;
    /** @var array $options */
    $options = ArrayUtils::merge($view->options ?: [], $options) ;
    return $view->url($view->route, $params, $options);
}

?>
<?php if ($this->pageCount > 1): ?>
    <ul class="pagination mt-20">

        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>

            <li>
                <a href="<?= $url($this, [], [
                    'query' => [
                        'page' => $this->previous
                    ]
                ]); ?>">
                    <i class="fa fa-angle-left"></i>
                </a>
            </li>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>

                <li>
                    <a href="<?= $url($this, [], [
                        'query' => [
                            'page' => $page
                        ]
                    ]); ?>">
                        <?= $page; ?>
                    </a>
                </li>
            <?php else: ?>
                <li class="active">
                    <a href="javascript: void(0);"><?= $page; ?></a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>

            <li>
                <a href="<?= $url($this, [], [
                    'query' => [
                        'page' => $this->next
                    ]
                ]); ?>">
                    <i class="fa fa-angle-right"></i>
                </a>
            </li>
        <?php endif; ?>
    </ul>
<?php endif; ?>