<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */

namespace MSBios\CPanel;

use Zend\Navigation\Page\Mvc;

?>
<ul class="navigation navigation-main navigation-accordion">

    <?php /** @var Mvc $page */ ?>
    <?php foreach ($this->container as $page): ?>

        <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) continue; ?>

        <?php $hasChildren = $page->hasPages(true); ?>
        <?php if (!$hasChildren): ?>

            <li class="<?php if ($page->isActive()): ?>active<?php endif; ?>">
                <a href="<?= $page->getHref(); ?>">
                    <i class="<?= $page->getClass(); ?>"></i>
                    <span><?= $this->translate($page->getLabel()); ?></span>
                </a>
            </li>
        <?php else: ?>

            <li class="<?php if ($page->isActive()): ?>active<?php endif; ?>">
                <a href="#">
                    <i class="<?= $page->getClass(); ?>"></i>
                    <span><?= $this->translate($page->getLabel()); ?></span>
                </a>

                <?php if($page->hasPages(true)): ?>
                    <ul>
                        <?php foreach ($page->getPages() as $child): ?>
                            <?php if (!$child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                            <?= $this->partial('partial/sidebar/nav.phtml', ['page' => $child]); ?>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>

            </li>


        <?php endif; ?>
    <?php endforeach; ?>
</ul>
