<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\CPanel;

use Zend\Navigation\Page\Mvc;

/** @var Mvc $page */
$page = $this->page;
$hasChildren = $page->hasPages(true);

?>

<li class="<?php if ($page->isActive()): ?>active<?php endif; ?>">
    <a href="<?= $hasChildren ?: $page->getHref() ?>">
        <?= $this->translate($page->getLabel()); ?>
    </a>

    <?php if ($hasChildren): ?>
        <ul>
            <?php foreach ($page->getPages() as $child): ?>
                <?php if (!$child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                <?= $this->partial('partial/sidebar/nav.phtml', ['page' => $child]); ?>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</li>