<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\CPanel;

/** @var Zend\Navigation\Page\Mvc $page */
$page = $this->page;
?>

<li class="<?php if ($page->isActive()): ?>active<?php endif; ?>">
    <a href="#"><?= $this->translate($page->getLabel()); ?></a>

    <?php if($page->hasPages(true)): ?>
        <ul>
            <?php foreach ($page->getPages() as $child): ?>
                <?php if (!$child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                <?= $this->partial('partial/sidebar/nav.phtml', ['page' => $child]); ?>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>

</li>
